### ISSUE TITLE
Creación del PDF para la solución del ejercicio

### ISSUE THREAD

**Issue by ivanosevic** [ivanosevic/alumni-ratio#11]
Se necesita crear el PDF para representar la solución final del ejercicio. Para esto, se usará la librería de iText PDF en Java. Esta libreria nos permite crear y editar documentos PDF en Java. Para leer más sobre la documentación, ver: https://itextpdf.com/resources/api-documentation/itext-7-java

Lo que se necesita en el PDF, es lo siguiente:

- Datos del ejercicio
- Transacciones
- Diario General
- Mayor General
- Balanza de comprobación

**Comment by armandonoel** [comment]
The General Ledger has been completed! We are going to implement the Trial Balance now.
