### ISSUE TITLE
Creación de clases y lógica para backend (Diario General)

### ISSUE THREAD

**Issue by ivanosevic** [ivanosevic/alumni-ratio#3]
Se tiene el siguiente diagrama de clases planteado:

![image](https://user-images.githubusercontent.com/24396014/221069580-10f9e7de-ba32-4f6f-935e-cf54d5830e45.png)

Ahora, se requiere implementarlo en el proyecto Java.

**Comment by armandonoel** [comment]
I've completed all my pending tasks. Please let me know if we need any change before we continue to the next step.

**Comment by armandonoel** [comment]
I've completed all my pending tasks. Please let me know if we need any change before we continue to the next step.
