### ISSUE TITLE
Integración backend con servidor web (Javalin)

### ISSUE THREAD

**Issue by ivanosevic** [ivanosevic/alumni-ratio#9]
Esta tarea requiere que se agregue la libreria Javalin. Esta libreria nos ayuda a crear una aplicación web en nuestro proyecto de Java.

Para ver los pasos de como agregar la librería, mirar la documentación: https://javalin.io/tutorials/maven-setup

Esta librería nos ayudará a comunicarnos con el frontend por medio del protocolo HTTP.

Se requiere un único endpoint hasta el momento: 

- Un endpoint con método POST, que tenga como cuerpo la información del ejercicio a resolver. Después de recibida la información, se necesita procesar el ejercicio y retornar el ejercicio resuelto. Para esto, es necesario que la tarea de Creación de la lógica para desarrollar el diario general este completa.

Para entender más sobre Rest API, leer el siguiente artículo: https://www.redhat.com/es/topics/api/what-is-a-rest-api
Para entender más sobre javalin, ver la documentación: https://javalin.io/documentation

**Comment by armandonoel** [comment]
The Javalin has been added to the project. We are going to add the post method now.
